name: Build and Push Docker Image.

on:
  push:
    branches: [ master ]  # Replace with your desired branch(es)

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Or a specific runner you prefer
    steps:
      - uses: actions/checkout@v3  # Checkout code from your repository
      - name: Login to Docker registry
        uses: docker/login-action@v2  # Login using Docker credentials
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

