name: Build and Push Docker Image

on:
  push:
    branches: [ master ]  # Replace with your desired branch(es)

jobs:
  test:  # Optional test job
    runs-on: ubuntu-latest  # Or a specific runner you prefer
    steps:
      - uses: actions/checkout@v3  # Checkout code from your repository
      - name: Install dependencies (if needed)
        run: |  # Adjust if you have dependencies
          # Example: Install Python dependencies
          sudo apt update && sudo apt install python3-pip
          pip install -r requirements.txt
      - name: Run tests  # Adjust command for your tests
        run: make test  # Or your specific test command

  build-and-push:  # Build and push image job
    runs-on: ubuntu-latest  # Or a specific runner you prefer
    services:
      dockerd:  # Define a Docker service
        image: docker:20.10.16-dind  # Use the same Docker version
        env:
          DOCKER_TLS_CERTDIR: /certs  # Set environment variable
    steps:
      - uses: actions/checkout@v3  # Checkout code from your repository
      - name: Login to Docker registry (optional)
        if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD  # Check for secrets
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u - --password-stdin
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .
      - name: Push Docker image (optional)
        if: secrets.IMAGE_NAME && secrets.IMAGE_TAG  # Check for secrets
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

